//! T043 (US9) — Orchestra XML → normalized `.fixdict` conversion tool.
#![cfg(feature = "dict-tooling")]

use truefix_dict::orchestra::{OrchestraError, convert};

const MINIMAL_FIXTURE: &str = r#"<?xml version="1.0"?>
<fixr:repository xmlns:fixr="http://fixprotocol.io/2020/orchestra/repository" version="FIX.Latest">
  <fixr:fields>
    <fixr:field id="8" name="BeginString" type="String"/>
    <fixr:field id="10" name="CheckSum" type="String"/>
    <fixr:field id="112" name="TestReqID" type="String"/>
    <fixr:field id="54" name="Side" type="char">
      <fixr:code value="1" name="Buy"/>
      <fixr:code value="2" name="Sell"/>
    </fixr:field>
  </fixr:fields>
  <fixr:components>
    <fixr:component id="1" name="StandardHeader">
      <fixr:fieldRef id="8"/>
    </fixr:component>
    <fixr:component id="2" name="StandardTrailer">
      <fixr:fieldRef id="10"/>
    </fixr:component>
  </fixr:components>
  <fixr:messages>
    <fixr:message name="TestRequest" msgType="1">
      <fixr:structure>
        <fixr:componentRef id="1"/>
        <fixr:fieldRef id="112" presence="required"/>
        <fixr:fieldRef id="54" presence="optional"/>
        <fixr:componentRef id="2"/>
      </fixr:structure>
    </fixr:message>
  </fixr:messages>
</fixr:repository>
"#;

const MINIMAL_EXPECTED: &str = "\
# Generated by truefix-dict's Orchestra conversion tool (US9) — do not edit by
# hand; regenerate from the Orchestra source fixture instead.
version FIX.Latest

field 8 BeginString STRING
field 10 CheckSum STRING
field 112 TestReqID STRING
field 54 Side CHAR 1=Buy 2=Sell

header 8
trailer 10

message 1 TestRequest req:112 opt:54
";

#[test]
fn converts_a_minimal_fixture_snippet_to_the_expected_normalized_text() {
    let got = convert(MINIMAL_FIXTURE).expect("convert");
    assert_eq!(got, MINIMAL_EXPECTED);
}

#[test]
fn the_converted_minimal_fixture_parses_as_a_valid_dictionary() {
    let text = convert(MINIMAL_FIXTURE).expect("convert");
    let dict = truefix_dict::parse(&text).expect("parse");
    assert_eq!(dict.version(), "FIX.Latest");
    assert!(dict.is_header(8));
    assert!(dict.is_trailer(10));
    let msg = dict.message("1").expect("TestRequest defined");
    assert!(msg.allows_tag(112));
    assert!(msg.allows_tag(54));
}

#[test]
fn unknown_field_type_errors_never_panic() {
    let xml = r#"<fixr:repository version="FIX.Latest">
        <fixr:fields><fixr:field id="1" name="Bogus" type="NotARealType"/></fixr:fields>
    </fixr:repository>"#;
    let err = convert(xml).unwrap_err();
    assert!(matches!(err, OrchestraError::UnknownType { .. }));
}

#[test]
fn unresolved_component_ref_errors_never_panic() {
    let xml = r#"<fixr:repository version="FIX.Latest">
        <fixr:messages>
          <fixr:message name="X" msgType="X">
            <fixr:structure><fixr:componentRef id="99"/></fixr:structure>
          </fixr:message>
        </fixr:messages>
    </fixr:repository>"#;
    let err = convert(xml).unwrap_err();
    assert!(matches!(
        err,
        OrchestraError::UnknownRef {
            kind: "component",
            ..
        }
    ));
}

#[test]
fn malformed_xml_errors_never_panic() {
    let err = convert("<fixr:repository version=\"FIX.Latest\"").unwrap_err();
    assert!(matches!(err, OrchestraError::Xml { .. }));
}

/// The bundled `FIXLATEST.orchestra.xml` fixture converts to exactly the shipped
/// `dict-src/normalized/FIXLATEST.fixdict` — proves the committed dictionary is not hand-drifted
/// from the tool that is supposed to have produced it (T046).
#[test]
fn the_bundled_orchestra_fixture_matches_the_shipped_fixlatest_dict() {
    let xml = include_str!("../dict-src/orchestra/FIXLATEST.orchestra.xml");
    let got = convert(xml).expect("convert bundled fixture");
    let shipped = include_str!("../dict-src/normalized/FIXLATEST.fixdict");
    assert_eq!(got, shipped);
    // And it must parse cleanly, exercising the group + component expansion end-to-end.
    let dict = truefix_dict::parse(&got).expect("parse bundled FIXLATEST.fixdict");
    let d = dict.message("D").expect("NewOrderSingle defined");
    assert!(
        d.contains_member(448),
        "Parties component's group member (448) reachable"
    );
}
