#!/usr/bin/env python3
"""Extract the pinned python-okx REST surface and bind it to Rust service methods."""

import ast
import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[3]
PY_ROOT = ROOT / "thrdpty/clientapi/python-okx/okx"
SERVICE_ROOT = ROOT / "crates/truefix-okx-client/src/services"
OUTPUT = ROOT / "crates/truefix-okx-client/src/generated_operation_inventory.rs"
SKIP = {"consts.py", "exceptions.py", "okxclient.py", "utils.py"}
PATH_OVERRIDES = {
    # Keep the generated manifest aligned with OKX's intentionally irregular
    # spellings in the pinned Python baseline.
    ("Account.py", "get_simulated_margin"): "/api/v5/account/simulated_margin",
    ("Account.py", "set_risk_offset_typel"): "/api/v5/account/set-riskOffset-type",
}
DOMAINS = {
    "BlockTrading.py": "block_trading",
    "CopyTrading.py": "copy_trading",
    "DualInvest.py": "dual_invest",
    "FDBroker.py": "fd_broker",
    "Finance/EthStaking.py": "eth_staking",
    "Finance/FlexibleLoan.py": "flexible_loan",
    "Finance/SolStaking.py": "sol_staking",
    "Finance/StakingDefi.py": "staking_defi",
    "MarketData.py": "market_data",
    "PublicData.py": "public_data",
    "SpreadTrading.py": "spread_trading",
    "SubAccount.py": "sub_account",
    "TradingData.py": "trading_data",
}


def constants():
    result = {}
    tree = ast.parse((PY_ROOT / "consts.py").read_text())
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        if not isinstance(node.targets[0], ast.Name):
            continue
        try:
            result[node.targets[0].id] = ast.literal_eval(node.value)
        except (ValueError, TypeError):
            pass
    return result


def rust_binding(path, sources):
    for source_path, source in sources.items():
        match = re.search(re.escape(path), source)
        if match:
            methods = re.findall(r"pub async fn\s+(\w+)", source[: match.start()])
            if methods:
                return f"{source_path.stem}::{methods[-1]}"
    return "UNSUPPORTED"


def quoted(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


values = constants()
services = {path: path.read_text() for path in SERVICE_ROOT.glob("*.rs")}
files = sorted([*PY_ROOT.glob("*.py"), *PY_ROOT.glob("Finance/*.py")])
rows = []
for path in files:
    relative = path.relative_to(PY_ROOT).as_posix()
    if path.name.startswith("_") or path.name in SKIP:
        continue
    tree = ast.parse(path.read_text())
    for cls in (node for node in tree.body if isinstance(node, ast.ClassDef)):
        for function in cls.body:
            if not isinstance(function, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if function.name.startswith("_"):
                continue
            call = next(
                (
                    node
                    for node in ast.walk(function)
                    if isinstance(node, ast.Call)
                    and isinstance(node.func, ast.Attribute)
                    and node.func.attr in {"_request_without_params", "_request_with_params"}
                ),
                None,
            )
            if call is None:
                continue
            method_arg, path_arg = call.args[:2]
            method = values[method_arg.id] if isinstance(method_arg, ast.Name) else ast.literal_eval(method_arg)
            source_path = values[path_arg.id]
            approved_path = PATH_OVERRIDES.get((relative, function.name), source_path)
            entrypoint = rust_binding(approved_path, services)
            domain = DOMAINS.get(
                relative, relative.removesuffix(".py").replace("Finance/", "").lower()
            )
            auth = "Public" if relative in {"MarketData.py", "PublicData.py", "Status.py"} else "Private"
            replay = "ReadOnly" if method == "GET" else "NeverReplay"
            rows.append(
                (f"{relative}:{function.lineno}:{function.name}", domain, function.name, method,
                 approved_path, auth, replay, entrypoint)
            )

if len(rows) != 264:
    raise SystemExit(f"expected 264 operations, extracted {len(rows)}")
unsupported = [row for row in rows if row[-1] == "UNSUPPORTED"]
if unsupported:
    raise SystemExit("unsupported baseline operations:\n" + "\n".join(map(str, unsupported)))

lines = [
    "// @generated by scripts/generate_operation_inventory.py; do not edit by hand.",
    "use super::{AuthClass, BaselineOperation, ReplayClass};",
    "pub const BASELINE_OPERATION_MANIFEST: &[BaselineOperation] = &[",
]
for source_id, domain, operation, method, path, auth, replay, entrypoint in rows:
    lines.extend([
        "    BaselineOperation {",
        f"        source_identity: {quoted(source_id)},",
        f"        domain: {quoted(domain)},",
        f"        operation: {quoted(operation)},",
        f"        method: {quoted(method)},",
        f"        path: {quoted(path)},",
        f"        auth: AuthClass::{auth},",
        f"        replay: ReplayClass::{replay},",
        f"        native_entrypoint: {quoted(entrypoint)},",
        '        fixture_id: "operation_inventory::baseline_manifest_is_complete_and_classified",',
        "    },",
    ])
lines.append("];")
OUTPUT.write_text("\n".join(lines) + "\n")
