//! Build-time codegen driver (dual-track, Constitution Principle IV).
//!
//! The actual parsing/codegen logic lives in `src/codegen.rs`, shared verbatim with the
//! `truefix-dict` CLI's `generate-code` subcommand (US13, FR-018) — a build script can't depend
//! on its own not-yet-built crate, so the *source file* is shared via `#[path]` instead of one
//! binary depending on the other. This file is just the driver: read each bundled dictionary,
//! call into the shared codegen, concatenate the results into `OUT_DIR/generated.rs`.

use std::env;
use std::fs;
use std::path::Path;

#[path = "src/codegen.rs"]
mod codegen;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let mut code = String::new();
    code.push_str("// @generated by build.rs from dict-src/normalized — do not edit.\n");

    for (name, file) in [
        ("FIX40", "FIX40.fixdict"),
        ("FIX41", "FIX41.fixdict"),
        ("FIX42", "FIX42.fixdict"),
        ("FIX43", "FIX43.fixdict"),
        ("FIX44", "FIX44.fixdict"),
        ("FIXT11", "FIXT11.fixdict"),
        ("FIX50", "FIX50.fixdict"),
        ("FIX50SP1", "FIX50SP1.fixdict"),
        ("FIX50SP2", "FIX50SP2.fixdict"),
        ("FIXLATEST", "FIXLATEST.fixdict"),
    ] {
        let path = Path::new(&manifest).join("dict-src/normalized").join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        codegen::emit_version(&mut code, name, &bytes)
            .unwrap_or_else(|e| panic!("codegen for {name}: {e}"));
    }

    let dest = Path::new(&out_dir).join("generated.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("write generated.rs: {e}"));
}
