//! Build-time codegen (dual-track, Constitution Principle IV).
//!
//! Reads the same normalized dictionary sources the runtime loads, and generates per-version
//! message-type constants plus a content hash. The runtime asserts its parsed hash equals the
//! generated one, proving codegen and runtime derive from one source.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in bytes {
        hash ^= u64::from(b);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let mut code = String::new();
    code.push_str("// @generated by build.rs from dict-src/normalized — do not edit.\n");

    for (name, file) in [
        ("FIX44", "FIX44.fixdict"),
        ("FIXT11", "FIXT11.fixdict"),
        ("FIX50", "FIX50.fixdict"),
    ] {
        let path = Path::new(&manifest).join("dict-src/normalized").join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let hash = fnv1a(&bytes);
        let _ = writeln!(code, "/// Content hash of the {name} dictionary source.");
        let _ = writeln!(code, "pub const {name}_DICT_HASH: u64 = {hash};");

        let module = name.to_lowercase();
        let _ = writeln!(
            code,
            "/// Generated MsgType constants for the {name} dictionary."
        );
        let _ = writeln!(code, "pub mod {module}_msgs {{");
        for line in String::from_utf8_lossy(&bytes).lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix("message ") {
                let mut it = rest.split_whitespace();
                if let (Some(msg_type), Some(msg_name)) = (it.next(), it.next()) {
                    let ident = msg_name.to_uppercase();
                    let _ = writeln!(code, "    /// MsgType for {msg_name}.");
                    let _ = writeln!(code, "    pub const {ident}: &str = {msg_type:?};");
                }
            }
        }
        let _ = writeln!(code, "}}");
    }

    let dest = Path::new(&out_dir).join("generated.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("write generated.rs: {e}"));
}
